### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by uccfd521** [andrealani/COOLFluiD#14]
Dear COOLFluiD Developers,

I've Installed COOLFluiD with no problem and it works fine, But in some examples, I've faced an error related to libMutation2Old.

I would be wondering if you could guide me on how to resolve this issue.

Thanks

**Comment by andrealani** [comment]
Mutation Old is not available in the open source distribution. If you want to use it, you have to follow the procedure which is explained in the HOWTO... I hope this helps

**Comment by vatsalyasharma** [comment]
Inactive thread, hence closing.
