### ISSUE TITLE
EXPERT testcase

### ISSUE THREAD

**Issue by zgbj0000zc** [andrealani/COOLFluiD#15]
Dear COOLFluiD Developers, 
I've installed COOLFluiD and I want to run a testcase named expertM13.5_postprocessing.CFcase. 
The path of the testcase is 'plugins/NEQ/testcases/TCNEQ/EXPERT3D/expertM13.5_postprocessing.CFcase'.

But I can not connnect the server to get the CFmesh file from vki, please tell me how should I do. 

Thanks.

**Comment by vatsalyasharma** [comment]
If the CFMesh file is not in the testcase folder, than it is not available for public use. Please feel free to check other test cases.
