### ISSUE TITLE
How to get the coordinate of cell's center in FVMCC?

### ISSUE THREAD

**Issue by zgbj0000zc** [andrealani/COOLFluiD#16]
Dear COOLFluiD Developers,

I want write a new scheme in COOLFluiD, but I can't get the coordinates of cell's center in FVMCC, please tell me how should I do.

Thanks.

**Comment by tracyjoker** [comment]
能向您请教一下怎么安装cool fluid吗，装了好就一直没装好

**Comment by zgbj0000zc** [comment]
回复晚了非常抱歉，请问是国内的CFD研究人员吗？如果你有使用和开发COOLFluiD的打算，可以加我的QQ详细交流一下。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tracyjoker"<notifications@github.com&gt;; 
发送时间: 2020年7月9日(星期四) 中午11:19
收件人: "andrealani/COOLFluiD"<COOLFluiD@noreply.github.com&gt;; 
抄送: "杨"<1269151772@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [andrealani/COOLFluiD] How to get the coordinate of cell&#39;s center in FVMCC? (#16)





 
能向您请教一下怎么安装cool fluid吗，装了好就一直没装好

**Comment by tracyjoker** [comment]
您好，我已经发送了好友请求，您通过一下，我是在安装coolfluid时遇到了一些问题。

**Comment by vatsalyasharma** [comment]
Inactive thread, hence closing.
