### ISSUE TITLE
MultiFluidMHD程序运行问题

### ISSUE THREAD

**Issue by tracyjoker** [andrealani/COOLFluiD#18]
尊敬的andrealani您好：
   我在复现您在2016年的工作《A fully-implicit finite-volume method for multi-fluid reactive and collisional magnetized plasmas on unstructured meshes》，但是在程序运行的过程中出现了如下的异常，请问我该如何解决？
From : '/home/tracy/share/src/Environment/Factory.hh:161:getProvider'
Type : 'NoSuchValueException'
Message :
In factory of [VarSetMatrixTransformer] a provider with the name [EulerMFMHD2DConsToRhoiViTiInRhoiViTi] was not found while trying to get the provider

From : '/home/tracy/share/src/Environment/Factory.hh:161:getProvider'
Type : 'NoSuchValueException'
Message :
In factory of [JacobianLinearizer] a provider with the name [EulerMFMHD2DLinearRhoiViTi] was not found while trying to get the provider

非常感谢您的帮助！

**Comment by qwebean** [comment]
他这个代码我很早就研究过了.缺失了很重要的一部分.除了他自己的电脑系统,根本无法编译成功的,不要浪费时间了.

**Comment by qwebean** [comment]
估计是发布代码前想隐藏一些关键代码,结果把那些代码排除后却忘了自己重新重头编译一遍.

**Comment by cescjf** [comment]
我编译好像没有问题的

**Comment by qwebean** [comment]
可能现在确实没问题。我当时编译都总是卡在最后一步，也许是配置环境或系统不对吧。

**Comment by yundantianchang** [comment]
当前程序这一部分模块尚未实现，框架调用的时候会提示有问题，不影响MFMHD计算结果。

**Comment by vatsalyasharma** [comment]
Inactive thread, hence closing.
