### ISSUE TITLE
Compilation and running problems

### ISSUE THREAD

**Issue by RomanovaDI** [andrealani/COOLFluiD#25]
Dear COOLFluid developers, I have got some problems with running COOLFluid:

1. There is no cmake-3.17.0 package which is required
2. There is no openmpi-4.0.3 package which is required
3. There is LagrangianSolver compilation error
4. There is RadiativeTransfer compilation error
5. stepFVMImpl.CFcase run problem: dlopen() failed to load module : libPetscI.so but all coolfluid dependancyes was installed
6. stepFVM_TimeAccurate.CFcase run problem: step.thor does not exist for DirectFileAccess: Success

Could you please help me to run stepFVMImpl case?

**Comment by vatsalyasharma** [comment]
Did you successfully install all the dependencies? 
It seems the dependencies have not been installed successfully (according to your point 1 and 2)
I request you to Please check : https://github.com/andrealani/COOLFluiD/wiki/HOWTO-install--dependencies

**Comment by vatsalyasharma** [comment]
Since there has been no response, I will close this thread.
