### ISSUE TITLE
Parallel Running  Error

### ISSUE THREAD

**Issue by RandallRain** [andrealani/COOLFluiD#27]
Dear COOLFluid developers, I have got a **parallel running error**. 

My OS is **Ubuntu 20.04**, the latest commit to `master` branch is a98fbc0 on Nov 8, 2022.

After installing dependencies, configuring and compiling this project, I parallelly run the  `jets2DFVMImpl.CFcase` test case with the following command:
```bash
mpirun -n 2 ./coolfluid-solver --scase ./jets2DFVMImpl.CFcase --log 750
```
**the error message**:
```bash
ParCFmeshFileReader::moveElementData() 10 => Memory usage: 5.24609 MB
ParCFmeshFileReader::moveElementData() 11 => Memory usage: 5.24609 MB
ParCFmeshFileReader::buildOverlapLayers() => start
ParCFmeshFileReader::buildOverlapLayers()
PEInterface<PM_MPI>::GetRank() => start
PEInterface<PM_MPI>::GetCommunicator()
PEInterface<PM_MPI>::GetRank() => end

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*************************ParCFmeshFileReader::buildOverlapLayers() => root [0]
**************************
ParCFmeshFileReader::buildOverlapLayers() => root [1]
/usr/include/c++/9/debug/vector:427:
In function:
    std::__debug::vector<_Tp, _Allocator>::reference 
    std::__debug::vector<_Tp, 
    _Allocator>::operator[](std::__debug::vector<_Tp, 
    _Allocator>::size_type) [with _Tp = unsigned int; _Allocator = 
    std::allocator<unsigned int>; std::__debug::vector<_Tp, 
    _Allocator>::reference = unsigned int&; std::__debug::vector<_Tp, 
    _Allocator>::size_type = long unsigned int]

Error: attempt to subscript container with out-of-bounds index 14301, but 
container only holds 14301 elements.

Objects involved in the operation:
    sequence "this" @ 0x0x7ffe6c17f6a8 {
      type = std::__debug::vector<unsigned int, std::allocator<unsigned int> >;
    }
```

I locate the error to this line of code:
```c++
  ElementDataArray<0>::Itr end = elem.getElement(m_nbElemPerProc[root]); // elem.end();
```
 in the `ParCFmeshFileReader::updateIsLocalNodeState()` method of `ParCFmeshFileReader.cxx` file, but don't know where and how to fix it.

The serial running is OK after adding `libShapeFunctions` to `Simulator.Modules.Libs` in `jets2DFVMImpl.CFcase`. The command is:
```bash
./coolfluid-solver --scase ./jets2DFVMImpl.CFcase --log 750
```

Thanks for your help.

**Comment by SimonShen2020** [comment]
There is 2 bugs in debug mode, this issue will not occour in optim mode, but it do happen in debug mode.

issue 1 : Framework/ElementDataArray.hh line 252
the vecor is out of range. when build the overlaplayer( in plugins/CFmeshFileReader/ParCFmeshFileReader.cxx) in function updateIsLocalNodeState (line 2483) , line 2508 ElementDataArray<0>::Itr end = elem.getElement(m_nbElemPerProc[root]);.
the end Iterator should be the next bit of the valid data, in optim mode the iterator is wild pointer, but in debug mode it will crash. 
Suggestion:  in line 2222 , change the vector size , plus 1 will fix this issue . 
                     tmpElem.resize(maxNbElemPerProc, maxElemSize + 1);
issue 2:  the pair function issue. when equal_range find nothing, it occurs.
             in file CFMutiMap.ci, line 72. change to below:
             isFound = (result.first->first ==result.first->second) ? false :  (result.first->first == aKey) ;

Hope it helps.
