### ISSUE TITLE
I want to develope a phase change solver based on COOLFluid. 

### ISSUE THREAD

**Issue by ztdepztdep** [andrealani/COOLFluiD#28]
The  phase change  problem will be solved based on FVM enthalpy method. Could y ou please give me some suggestions.

**Comment by vatsalyasharma** [comment]
Please start with finitevolumenavierstokes plugin. Use the documentation to navigate your way. 
You can also check the latest papers from our group on FR, especially by Ray. He developed a compressible flow solver in FR, which you can modify for your needs.

**Comment by vatsalyasharma** [comment]
No response by the user. They can open new thread if required.
