### ISSUE TITLE
New Version?

### ISSUE THREAD

**Issue by stefano2734** [andrealani/COOLFluiD#31]
I see a paper from 2019
https://www.nas.nasa.gov/assets/nas/pdf/ams/2019/AMS_20191029_Lani.pdf

I see this paper of year 2024 with extended FR solver.

https://www.sciencedirect.com/science/article/abs/pii/S001046552300351X

or is it in a fork?

**Comment by vatsalyasharma** [comment]
@RayanDhib

**Comment by RayanDhib** [comment]
All developments and extensions of the FR solver are committed to the main repository; there are no separate forks for these updates.

**Comment by vatsalyasharma** [comment]
Since the question has been answered, I am closing the issue

**Comment by stefano2734** [comment]
It starts here 2017 with Version 2.0.0.

So a new version orbupdate is in most software projects 2.0.1 or 3.0.0.
