### ISSUE TITLE
fblaslapack is no longer available in packages

### ISSUE THREAD

**Issue by amunozj** [andrealani/COOLFluiD#9]
The script ./install-coolfluid-deps.pl

Can't find fblaslapack-3.1.1.tar.gz nor download it from the github repository.  I downloaded it from here.  Maybe a repository like this can be added to the script:

http://ftp.mcs.anl.gov/pub/petsc/externalpackages/fblaslapack-3.1.1.tar.gz

**Comment by andrealani** [comment]
Which version of Petsc are you using? I had no problems up to petsc 3.9.0 ... I will try your patch and if it doesn't break existing installation I will integrate it ...Sorry, but I haven't checked this in a while...

**Comment by munafo** [comment]
Hi,

I am actually using PETSC 3.9 (not within COOLFLuiD) and installed it using fblaslapack version 3.4.2. Below you find an installation scripts (which I used on the Solo machine at SNL). Note that I had to download manually fblaslapack as for my case the firewall would prevent to download it when writing only:

-download-fblaslapack

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#!/bin/bash
set -e

MAJOR=3
MINOR=9
MICRO=1
VERSION=$MAJOR.$MINOR

tar -xvf petsc-$VERSION.$MICRO.tar.gz

BASE_DIR=/home/amunafo/workspace/libraries/petsc

INSTALL_DIR=$BASE_DIR/petsc-3.9-$COMPILER-$COMPILER_VERSION-$MPI_IMPLEMENTATION-$MPI_VERSION
echo $INSTALL_DIR

cd petsc-$VERSION.$MICRO

./configure FC=mpif90 CC=mpicc CXX=mpicxx --download-fblaslapack=$BASE_DIR/fblaslapack-3.4.2.tar.gz  --with-parmetis-dir=$INSTALL_DIR --with-metis-dir=$INSTALL_DIR --with-debugging=0 COPTFLAGS='-O3 -march=native -mtune=native' CXXOPTFLAGS='-O3 -march=native -mtune=native' FOPTFLAGS='-O3 -march=native -mtune=native' --prefix=$INSTALL_DIR
make
make install

cd ..
rm -fr petsc-$VERSION.$MICRO

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Best,

Alessandro

________________________________

**Comment by andrealani** [comment]
Thanks, in fact I got a patch from a collaborator that foxes the problem but I wanted to test it first!

Alessandro, come stai???

**Comment by munafo** [comment]
Bene, grazie tu come stai? Mi sa che l'ultima volta che ci siamo visti in carne ed ossa era alla nasa 3 anni fa quando abbiamo pluggato plato in CF per la prima volta (eravamo al redrock cafe).

Sto ancora lavorando nel centro PSAAP II con Marco, ma ho cominciando a cercare altro. Ho imparato molto in questi ultimi due anni (HPC, numerics, laser and plasma modeling...). Il problema e' che e' difficile focalizzarsi sulla propria ricerca e pubblicare (c'e' sempre da fare della roba per le predictions soprattutto quando arriva la review).

Stammi bene,

Best,

Alessandro

________________________________
